version: "2"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/rom-rb/devtools/master/.rubocop.yml"
    path: ".rubocop.yml"

exclude_patterns:
  - "benchmarks/"
  - "examples/"
  - "spec/"
  - "*/spec/"
  - "*/examples/"
  - "*/benchmarks/"
  - "!*.rb"

plugins:
  rubocop:
    enabled: true
