language: ruby
sudo: false
cache: bundler
before_install: gem update --system
services:
  - elasticsearch
bundler_args: --without yard guard benchmarks tools
before_script:
  - curl -XPUT http://localhost:9200/rom-test
after_success:
  - "[ -d coverage ] && bundle exec codeclimate-test-reporter"
script: "bundle exec rake ci"
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.1.12.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
