language: ruby
sudo: false
cache: bundler
before_install: gem update --system
services:
  - elasticsearch
bundler_args: --without yard guard benchmarks tools
before_script:
  - curl -XPUT http://localhost:9200/rom-test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script: "bundle exec rake ci"
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - jruby-head
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
