---
name: ci
'on':
  push:
    paths:
    - ".github/workflows/ci.yml"
    - ".github/workflows/custom/ci.yml"
    - lib/**
    - "*.gemspec"
    - spec/**
    - Rakefile
    - Gemfile
    - Gemfile.devtools
    - ".rubocop.yml"
    - project.yml
  pull_request:
    branches:
    - master
  create: 
jobs:
  tests:
  - name: Configure sysctl limits
    run: |
      sudo swapoff -a
      sudo sysctl -w vm.swappiness=1
      sudo sysctl -w fs.file-max=262144
      sudo sysctl -w vm.max_map_count=262144
  - name: Runs Elasticsearch
    uses: elastic/elastic-github-actions/elasticsearch@master
    with:
      stack-version: 6.8.2
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags') && github.event_name == 'create'
    needs: tests
    env:
      GITHUB_LOGIN: rom-bot
      GITHUB_TOKEN: "${{secrets.GH_PAT}}"
    steps:
    - uses: actions/checkout@v1
    - name: Install package dependencies
      run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install ossy --no-document
    - name: Trigger release workflow
      run: |
        tag=$(echo $GITHUB_REF | cut -d / -f 3)
        ossy gh w rom-rb/devtools release --payload "{\"tag\":\"$tag\",\"tag_creator\":\"$GITHUB_ACTOR\",\"repo\":\"$GITHUB_REPOSITORY\"}"
