---
name: ci
'on':
  push:
    paths:
    - ".github/workflows/ci.yml"
    - ".github/workflows/custom/ci.yml"
    - lib/**
    - "*.gemspec"
    - spec/**
    - Rakefile
    - Gemfile
    - Gemfile.devtools
    - ".rubocop.yml"
    - project.yml
  pull_request:
    branches:
    - master
  create:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.0'
        - '2.7'
        - '2.6'
        - '2.5'
        - jruby
        include:
        - ruby: '3.0'
          coverage: 'true'
    env:
      COVERAGE: "${{matrix.coverage}}"
      COVERAGE_TOKEN: "${{secrets.CODACY_PROJECT_TOKEN}}"
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags') && github.event_name == 'create'
    needs: tests
    env:
      GITHUB_LOGIN: rom-bot
      GITHUB_TOKEN: "${{secrets.GH_PAT}}"
    steps:
    - uses: actions/checkout@v1
    - name: Install package dependencies
      run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install ossy --no-document
    - name: Trigger release workflow
      run: |
        tag=$(echo $GITHUB_REF | cut -d / -f 3)
        ossy gh w rom-rb/devtools release --payload "{\"tag\":\"$tag\",\"tag_creator\":\"$GITHUB_ACTOR\",\"repo\":\"$GITHUB_REPOSITORY\"}"
